-- MySQL Script generated by MySQL Workbench
-- Tue Feb  4 15:54:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `cliente` (
  `cod_cliente` INT NOT NULL COMMENT 'Essa é a chave primária desta tabela',
  `nome_cliente` VARCHAR(50) NOT NULL COMMENT 'Tem como o objetivo guardar o nome do cliente',
  `endereço` VARCHAR(50) NOT NULL COMMENT 'Tem como objetivo guardar o endereço do cliente\n',
  `cidade` VARCHAR(50) NOT NULL COMMENT 'Tem como objetivo guardar a cidade do cliente\n',
  `cep` VARCHAR(10) NOT NULL COMMENT 'tem como o objetivo guardar o cep do cliente',
  `uf` CHAR(2) NOT NULL COMMENT 'Tem como objetivo guardar a unidade federativa do cliente',
  `cnpj` VARCHAR(30) NOT NULL COMMENT 'Tem cmo o objetivo guardar a cnpj do cliente',
  `ie` INT NOT NULL,
  PRIMARY KEY (`cod_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vendedor` ;

CREATE TABLE IF NOT EXISTS `Vendedor` (
  `cod_vendedor` INT NOT NULL COMMENT 'Tem como objetivo armazenar o codigo do vendedor\n',
  `nome_vendedor` VARCHAR(50) NOT NULL COMMENT 'Armazena o nome do  vendedor',
  `sal_fixo` DECIMAL(15,2) NOT NULL COMMENT 'Armazena o slaário fixo, do vendedor',
  `faixa_comissão` CHAR(2) NOT NULL COMMENT 'Armazena a comissão que o vendedor receberá\n',
  PRIMARY KEY (`cod_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido` ;

CREATE TABLE IF NOT EXISTS `Pedido` (
  `num_pedido` INT NOT NULL COMMENT 'Armazena o número do pedido\n',
  `prazo_entrega` INT NOT NULL COMMENT 'Tem como objetivo armazenar o prazo de entrega do pedido',
  `cliente_cod_cliente` INT NOT NULL COMMENT 'É a chave primária da tabela cliente',
  `Vendedor_cod_vendedor` INT NOT NULL COMMENT 'É a chave primária da tabela vendedor',
  PRIMARY KEY (`num_pedido`),
  INDEX `fk_Pedido_cliente_idx` (`cliente_cod_cliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Vendedor1_idx` (`Vendedor_cod_vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_cliente`
    FOREIGN KEY (`cliente_cod_cliente`)
    REFERENCES `mydb`.`cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Vendedor1`
    FOREIGN KEY (`Vendedor_cod_vendedor`)
    REFERENCES `mydb`.`Vendedor` (`cod_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `cod_produto` INT NOT NULL COMMENT 'armazena o código do produto',
  `unid_produto` VARCHAR(10) NOT NULL COMMENT 'Armazena a unidade de medida do produto',
  `desc_produto` VARCHAR(50) NOT NULL,
  `valor_unit` DECIMAL(15,2) NOT NULL COMMENT 'Armazena qual o valor por unidade do produto',
  PRIMARY KEY (`cod_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item de pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item de pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item de pedido` (
  `Pedido_num_pedido` INT NOT NULL COMMENT 'É a chave primária de pedido',
  `Produto_cod_produto` INT NOT NULL,
  `quantidadeproduto` INT NOT NULL COMMENT 'armazena a quantidade do produto\n',
  PRIMARY KEY (`Pedido_num_pedido`, `Produto_cod_produto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_cod_produto` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`Pedido_num_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`Pedido_num_pedido`)
    REFERENCES `mydb`.`Pedido` (`num_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_cod_produto`)
    REFERENCES `mydb`.`Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
